version: "3.8"
#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
services:
  worker:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: ${AWSLOGS_AIRBYTE_GROUP}
        awslogs-stream: worker

  server:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: ${AWSLOGS_AIRBYTE_GROUP}
        awslogs-stream: server